### ISSUE TITLE
Issue running basic_callbacks_events.py

### ISSUE THREAD

**Issue by cpsievert** [plotly/dash-docs#39]
No graph appears and I see

```python
 python dash-docs/tutorial/examples/basic_callbacks_events.py 
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 275-473-831
127.0.0.1 - - [11/Dec/2017 17:53:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Dec/2017 17:54:02] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Dec/2017 17:54:02] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [11/Dec/2017 17:54:03] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [11/Dec/2017 17:54:08] "POST /_dash-update-component HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/dash/dash.py", line 551, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/dash/dash.py", line 508, in add_context
    output_value = func(*args, **kwargs)
  File "/Users/cpsievert/github/dash-docs/tutorial/examples/basic_callbacks_events.py", line 45, in update_graph
    dt(2017, 1, 1), dt.now()
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/pandas_datareader/data.py", line 137, in DataReader
    session=session).read()
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/Users/cpsievert/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?output=csv&startdate=Jan+01%2C+2017&enddate=Dec+11%2C+2017&q=COKE
```

**Comment by chriddyp** [comment]
@cpsievert  - Try using Python 2 to start, and then do `pip install -r requirements.txt`. Once it's running, visit https://localhost:8050/dash/

**Comment by cpsievert** [comment]
Thanks, I did the following: 

```python
/usr/local/bin/python2 ~/anaconda/bin/pip install -r requirements.txt
```

Yet, I still see same error -- could it be a problem with pandas_datareader?

```python2
python2 ./tutorial/examples/basic_callbacks_events.py 
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 493-914-212
127.0.0.1 - - [13/Dec/2017 11:25:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2017 11:25:15] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2017 11:25:15] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2017 11:25:15] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [13/Dec/2017 11:25:31] "POST /_dash-update-component HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/usr/local/lib/python2.7/site-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "/Users/cpsievert/github/dash-docs/tutorial/examples/basic_callbacks_events.py", line 45, in update_graph
    dt(2017, 1, 1), dt.now()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/data.py", line 132, in DataReader
    session=session).read()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 155, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 74, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 85, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 120, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?q=COKE&startdate=Jan+01%2C+2017&enddate=Dec+13%2C+2017&output=csv
```

**Comment by chriddyp** [comment]
Hm yeah it could be. It looks like pandas datareader is having some issues now (https://github.com/pydata/pandas-datareader/issues/394)

In fact, that example isn't actually used in the docs anymore (the concept of `events` isn't documented anymore as all of the components now have property based alternatives)

**Comment by ned2** [comment]
@chriddyp, since events are being phased out, should we just remove this example from the examples directory?
