### ISSUE TITLE
Example on https://dash.plotly.com/layout does not work

### ISSUE THREAD

**Issue by np-8** [plotly/dash-docs#929]
Hi, 

Simple copy-paste of the example at [https://dash.plotly.com/layout](https://dash.plotly.com/layout) does not work. 

## Code 

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# assume you have a "wide-form" data frame with no index
# see https://plotly.com/python/wide-form/ for more options
df = pd.DataFrame({"x": [1, 2, 3], "SF": [4, 1, 2], "Montreal": [2, 4, 5]})

fig = px.bar(df, x="x", y=["SF", "Montreal"], barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

## Traceback

```python
Traceback (most recent call last):
  File ".\test.py", line 15, in <module>
    fig = px.bar(df, x="x", y=["SF", "Montreal"], barmode="group")
  File "C:\Python\Python37\lib\site-packages\plotly\express\_chart_types.py", line 313, in bar
    layout_patch=dict(barmode=barmode),
  File "C:\Python\Python37\lib\site-packages\plotly\express\_core.py", line 1368, in make_figure
    args, constructor, trace_patch
  File "C:\Python\Python37\lib\site-packages\plotly\express\_core.py", line 1211, in infer_config
    args = build_dataframe(args, all_attrables, array_attrables)
  File "C:\Python\Python37\lib\site-packages\plotly\express\_core.py", line 1022, in build_dataframe
    % (field, len(argument), str(list(df_output.columns)), length)
ValueError: All arguments should have the same length. The length of argument `y` is 2, whereas the length of previous arguments ['x'] is 3
```

Versions
```
plotly                    4.6.0
dash                      1.10.0
dash-bootstrap-components 0.9.2
dash-core-components      1.9.0
dash-html-components      1.0.3
dash-renderer             1.3.0
dash-table                4.6.2
```

**Comment by alexcjohnson** [comment]
Hi @np-8 - sorry that this error message is not very helpful. Wide-form data handling was added to `plotly.express` in v4.8.0, I think you just need to upgrade `plotly`.
